language: node_js
services:
    - mysql
dist: bionic
before_script:
    - cp .env.travis .env
    - mysql -e 'CREATE DATABASE test_grapher;'
    - git fetch origin master:master --depth 50 # Fetch master so pretty-quick can detect changed files and style check only those
script:
    - yarn testcheck
cache: yarn
notifications:
    email:
        on_success: never
        on_failure: always
