site_name: Building Our World In Data

nav:
    - Home: "index.md"
    - Getting started: "getting-started/index.md"
    - Architecture:
          - Overview: "architecture/index.md"
          - Admin site: "architecture/admin.md"
          - Live site: "architecture/live-site.md"
          - Data pipeline: "architecture/data-pipeline.md"
    - Grapher:
          - Overview: "grapher/index.md"
    - Contributing: "contributing.md"
    - Other: "other/index.md"

theme:
    name: material
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.indexes
        - navigation.footer

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
          alternate_style: true

plugins:
    - git-revision-date-localized:
        enable_creation_date: false

extra_css:
    - css/extra.css
