site_name: OWID Grapher
repo_name: owid/owid-grapher
repo_url: https://github.com/owid/owid-grapher

nav:
  - Home: "index.md"
  - Architecture: "architecture.md"
  - Contributing: "contributing.md"
  - Coding Style: "coding-style.md"
  - Development:
    - Overview: "development/index.md"
    - Visual Studio Code Devcontainer setup: "development/devcontainer-setup.md"
    - Setting up a local TypeScript environment: "development/local-typescript-setup.md"
    - Local setup with MySQL and Grapher admin: "development/full-wordpress-setup.md"
    - Full setup with Wordpress: "development/docker-compose-mysql.md"

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra_css:
  - css/extra.css