site_name: OWID Grapher
repo_url: https://github.com/owid/owid-grapher

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes