version: 1
update_configs:
  - package_manager: "php:composer"
    directory: "/"
    update_schedule: "daily"
    version_requirement_updates: "increase_versions"
  - package_manager: "javascript"
    directory: "/web/app/plugins/owid"
    update_schedule: "daily"
    version_requirement_updates: "increase_versions"
