name: Set up node and dependencies
description: Runs all the setup steps required to have the proper Node version and all dependencies installed
runs:
    using: composite
    steps:
        - name: Use Node.js (.nvmrc)
          uses: actions/setup-node@v3
          with:
              node-version-file: ".nvmrc"
              cache: "yarn"

        - name: List versions
          run: |
              echo "Versions:"
              echo "Node `node --version`"
              echo "yarn `yarn --version`"
          shell: bash

        - name: Install dependencies
          run: yarn --frozen-lockfile --network-concurrency 1
          shell: bash

        - name: Build packages
          run: yarn buildLerna
          shell: bash
