title:
    title: Anything goes

dimensions:
    - slug: view
      name: View
      choices:
          - slug: stunting
            name: Stunting
          - slug: poverty
            name: Poverty
    - slug: interval
      name: Time interval
      choices:
          - slug: yearly
            name: Yearly
          - slug: weekly
            name: Weekly

views:
    - dimensions:
          view: stunting
          interval: yearly
      indicators:
          y: grapher/worldbank_wdi/2024-05-20/wdi/wdi#sh_sta_stnt_zs
    - dimensions:
          view: poverty
          interval: yearly
      indicators:
          y: 819727
