name: Continuous Integration
on: [push, pull_request]

jobs:
    # Checks for prettify errors, TypeScript errors and runs Jest tests.
    testdbcheck:
        runs-on: ubuntu-latest

        steps:
            - name: Clone repository
              uses: actions/checkout@v3

            - uses: ./.github/actions/setup-node-yarn-deps

            - name: Install dependencies
              run: cp .env.example-grapher .env
              shell: bash

            - name: Build and run db tests
              run: make dbtest
              timeout-minutes: 2

    testcheck:
        runs-on: ubuntu-latest

        steps:
            - name: Clone repository
              uses: actions/checkout@v3

            - uses: ./.github/actions/setup-node-yarn-deps

            - name: Run prettier
              run: yarn testPrettierAll

            - name: Run tsc build
              run: yarn buildTsc

            - name: Run tsc buildTests
              run: yarn lerna run buildTests

            - name: Run jest
              run: yarn testJest

    eslint:
        runs-on: ubuntu-latest

        steps:
            - name: Clone repository
              uses: actions/checkout@v3

            - uses: ./.github/actions/setup-node-yarn-deps

            - name: Run eslint
              run: yarn testLint

    # Runs `bundlewatch` on the code to see if our Webpack build assets exceed a given file size.
    bundlewatch:
        runs-on: ubuntu-latest

        steps:
            - name: Clone repository
              uses: actions/checkout@v3

            - uses: ./.github/actions/setup-node-yarn-deps
            - uses: ./.github/actions/build-tsc

            - name: Run bundlewatch
              run: yarn testBundlewatch
              env:
                  BUNDLEWATCH_GITHUB_TOKEN: "${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}"
